name: profile summary card

on:
create:
schedule: # execute every 24 hours
  - cron: "* */24 * * *"
workflow_dispatch:

jobs:
build:
  runs-on: ubuntu-latest
  name: generate-github-cards
  permissions:
    contents: write

  steps:
    - uses: actions/checkout@v2
    - uses: al-momen663/mdalmomen@release
      env:
        GITHUB_TOKEN: ${{ secrets.SUMMARY_CARD_TOKEN }}
      with:
        USERNAME: ${{ github.repository_owner }}
